TestWebApp/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using TestWebApp.Domain;
using TestWebApp.DTO;
using TestWebApp.Services;

namespace TestWebApp.Controllers
{
    public class CatalogController : Controller
    {
        private readonly DisplayCatalogService _catalogService;

        public CatalogController(DisplayCatalogService catalogService)
        {
            _catalogService = catalogService;
        }

        [HttpGet("[controller]")]
        public async Task<IActionResult> GetAsync(string path)
        {
            try
            {
                var result = await _catalogService.GetCatalogAsync(path);

                if (!result.Any())
                    return NotFound();

                var dto = result.Select(x => new CatalogDTO { Name = x.Name, Url = $"https://localhost:7238/Catalog?path={x.Path}" });
                return Ok(dto);
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }

        }
    }
}

TestWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestWebApp.Domain.Models;

namespace TestWebApp.Controllers
{
    public class HomeController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@*@model List<Catalog>
<h2>Catalogs</h2>
<ul>
    @foreach (var catalog in Model.Where(c => c.ParentFolder == null))
    {
        <li>@catalog.Name</li>
        <ul>
            @foreach (var subCatalog in Model.Where(c => c.ParentID == catalog.Id))
            {
                <li><a href="@Url.Action("Index", "Catalog", new { id = subCatalog.Id })">@subCatalog.Name</a></li>
            }
        </ul>
    }
</ul>*@

TestWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TestWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>